FROM alpine:3.13 as builder
COPY ./tmp/packages ./tmp
RUN cp /tmp/apache_mod_h264_streaming-2.2.7.tar.gz  ~/apache_mod_h264_streaming-2.2.7.tar.gz
RUN cd ~ && tar -zxvf apache_mod_h264_streaming-2.2.7.tar.gz
RUN apk update --no-cache
RUN apk add linux-headers
RUN apk add g++
RUN apk add make
RUN apk add build-base
RUN apk add apache2-dev=2.4.46-r3
RUN cd ~ && tar -zxvf apache_mod_h264_streaming-2.2.7.tar.gz
RUN cd ~/mod_h264_streaming-2.2.7 && ./configure --with-apxs=`which apxs2` && make && make install
RUN rm /etc/apache2/httpd.conf
COPY ./tmp/conf/httpd.conf /etc/apache2/httpd.conf
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
EXPOSE 80
